package ma.cremelogic.CremeLogic.ma.enums;

public enum TypeAlerte {
    STOCK_FAIBLE,
    DATE_EXPIRATION,
    COMMANDE_RETARD,
    COMMANDE_ANNULEE,
    PRODUCTION_RETARD,
    PRODUCTION_ANNULEE,
    VENTE_EXCEPTIONNELLE,
    VENTE_ANNULEE,
    PERTE_STOCK,
    ALERTE_SECURITE,
    PRODUCTION_TERMINEE,
    PROBLEME_SIGNALE,
    NOUVELLE_COMMANDE
}
